20 feature login basiuk
Social-projects-Rivne/U4U_Client pull request #12
Opened 2019-10-12 16:30 UTC by DMTRIP

2019-10-13 13:37 UTC, Viktor-Hordynskyi approved these changes

2019-10-14 15:05 UTC, victorpoliushko approved these changes
Advices:
- format your src/components/page/login/login.js file
- add " text-align: center; " for class title in src/components/page/login/login.scss

2019-10-14 20:57 UTC, AndriiDruzhytskyi requested changes
I have some problems when try to pass request to server, please tell me more about your configuration via Slack.
![image](https://user-images.githubusercontent.com/46317684/66782310-17be2b00-eede-11e9-8715-b7c1e3a1edea.png)

2019-10-14 20:57 UTC, MelodyCode commented on src/components/header/header.js
> +  console.log(isAuth);
Do you need this console output in dev?

2019-10-14 20:57 UTC, MelodyCode commented on src/components/page/login/login.js
> +                                onFocu
Is this a typo??

2019-10-15 10:57 UTC, DMTRIP commented on src/components/header/header.js
> +  console.log(isAuth);
No I'll remove the line

2019-10-15 10:57 UTC, DMTRIP commented on src/components/page/login/login.js
> +                                onFocu
+

2019-10-16 06:16 UTC, AndriiDruzhytskyi approved these changes
After this pull request merged:

1. We must resolve port number mismatch on anouther task.
2. Resolve routing when user set tokens locally.
3. Resolve routing when triggers a refresh token logic.

2019-10-16 14:54 UTC, merged